name: Deploy to Coolify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"
        OPENAI_API_KEY: "test-key"
        FACEBOOK_APP_ID: "test-id"
        WHATSAPP_TOKEN: "test-token"
        JWT_SECRET: "test-secret-key-for-github-actions"
        ENCRYPTION_KEY: "test-encryption-key-32-chars-long"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Coolify
      run: |
        echo "🚀 Deployment will be handled by Coolify webhook"
        echo "✅ Code pushed to main branch successfully"